---
- name: Setup Raspberry Pi
  hosts: pi
  remote_user: root
  gather_facts: no
  vars:
      ansible_ssh_pass: raspbian
  tasks:
      - name: Wait for ssh
        local_action: wait_for
              host="{{ ansible_ssh_host }}"
              port=22
              timeout=50000

      - name: Remove known host
        local_action: command ssh-keygen -R {{ ansible_ssh_host }}

      - name: Check python
        action: ping
        register: python_installed
        no_log: yes
        ignore_errors: yes

      - name: Install python
        raw: apt-get update && apt-get -y install python
        when: python_installed|failed

      - action: setup

      - name: Add user
        user: name=lbischof shell=/bin/bash groups=sudo append=yes 

      - name: Install sudo
        apt: name=sudo 

      - name: Enable passwordless sudo
        lineinfile: "dest=/etc/sudoers line='lbischof ALL=(ALL) NOPASSWD: ALL'"

      - name: Add public key
        authorized_key: user=lbischof key=https://github.com/lbischof.keys

      - name: Import gpg key
        local_action: command gpg --export-secret-key AFBA32A6 | ssh lbischof@{{ ansible_ssh_host }} gpg --import

      - name: Lock root account
        command: passwd -l root
      
- include: pi.yml
