---

- name: Install wake on lan script
  copy: src=pc.sh dest=/usr/local/bin/pc mode=0755
  sudo: True

- name: Install ip_changed script
  copy: src=ip_changed.sh dest=/usr/local/bin/ip_changed mode=0755
  sudo: True

- name: Install apps
  apt: name={{ item }}
  sudo: True
  with_items:
    - fail2ban
    - vim
    - dnsutils
    - wakeonlan
    - netcat

- cron: name="check ip" minute="*/10" job="ip_changed"
